name: OpenSSF Scorecard

on:
  # once a week, every sunday at 00:00
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches: [ "main", "master" ]
  # enable manual activation from Actions tab
  workflow_dispatch:

# remove all global permissions
permissions: {}

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read

    steps:
      - name: "Checkout code"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: "Run analysis"
        uses: ossf/scorecard-action@f49aabe0b5af0936a0987cfb85d86b75731b0186 # v2.4.2
        with:
          results_file: results.sarif
          results_format: sarif
          # publish results to OpenSSF (generates Badge for the README file)
          publish_results: true

      # upload report to Security -> Code Scanning tab in github web
      - name: "Upload artifact"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5

      # for some envs v3 has better compatibility
      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28 # v4.37.8
        with:
          sarif_file: results.sarif
